# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

main_vb_cam_cpp <- function(Y_grouped, L, K, J, XI_ijl, RHO_jk, Nj, m0, k0, a0, b0, ml, kl, al, bl, a_tilde, b_tilde, a_bar, b_bar, epsilon, maxSIM, verbose = 0L) {
    .Call(`_SANvi_main_vb_cam_cpp`, Y_grouped, L, K, J, XI_ijl, RHO_jk, Nj, m0, k0, a0, b0, ml, kl, al, bl, a_tilde, b_tilde, a_bar, b_bar, epsilon, maxSIM, verbose)
}

main_vb_cam_CP_cpp <- function(Y_grouped, L, K, J, XI_ijl, RHO_jk, Nj, m0, k0, a0, b0, ml, kl, al, bl, conc_hyper, epsilon, maxSIM, verbose = 0L) {
    .Call(`_SANvi_main_vb_cam_CP_cpp`, Y_grouped, L, K, J, XI_ijl, RHO_jk, Nj, m0, k0, a0, b0, ml, kl, al, bl, conc_hyper, epsilon, maxSIM, verbose)
}

main_vb_fSAN_cpp <- function(Y_grouped, L, K, J, XI_ijl, RHO_jk, Nj, m0, k0, a0, b0, ml, kl, al, bl, alpha_bar, beta_bar, epsilon, maxSIM, verbose = 0L) {
    .Call(`_SANvi_main_vb_fSAN_cpp`, Y_grouped, L, K, J, XI_ijl, RHO_jk, Nj, m0, k0, a0, b0, ml, kl, al, bl, alpha_bar, beta_bar, epsilon, maxSIM, verbose)
}

main_vb_fiSAN_cpp <- function(Y_grouped, L, K, J, XI_ijl, RHO_jk, Nj, m0, k0, a0, b0, ml, kl, al, bl, a_tilde, b_tilde, beta_bar, epsilon, maxSIM, verbose = 0L) {
    .Call(`_SANvi_main_vb_fiSAN_cpp`, Y_grouped, L, K, J, XI_ijl, RHO_jk, Nj, m0, k0, a0, b0, ml, kl, al, bl, a_tilde, b_tilde, beta_bar, epsilon, maxSIM, verbose)
}

main_vb_fiSAN_CP_cpp <- function(Y_grouped, L, K, J, XI_ijl, RHO_jk, Nj, m0, k0, a0, b0, ml, kl, al, bl, conc_hyper, beta_bar, epsilon, maxSIM, verbose = 0L) {
    .Call(`_SANvi_main_vb_fiSAN_CP_cpp`, Y_grouped, L, K, J, XI_ijl, RHO_jk, Nj, m0, k0, a0, b0, ml, kl, al, bl, conc_hyper, beta_bar, epsilon, maxSIM, verbose)
}

